db:
  image: mongo
  ports: 
   - "27017:27017"
mongo-importer:
  build: . 
  links: 
  - db
web:
  build: ./web
  links:
   - db
  ports:
   - "3000:3000"
  volumes:
   - ./src:/home/env
  environment:
   NODE_ENV: development
ionic:
 build: ./ion
 command: /bin/bash
 ports:
  - "8100:8100" 
  - "35729:35729"
 
